apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: trm1auskg-python
  janus-idp.io/tekton: trm1auskg-python
  backstage.io/kubernetes-id: trm1auskg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: trm1auskg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
