apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: trm1auskg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trm1auskg-python 
  name: trm1auskg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: trm1auskg-python 
